/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostBookingsRouteImport } from './routes/host.bookings'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/host/bookings',
  path: '/host/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/host/bookings': typeof HostBookingsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/host/bookings': typeof HostBookingsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/host': typeof HostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/host/bookings': typeof HostBookingsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-confirmed'
    | '/bookings'
    | '/favorites'
    | '/reviews'
    | '/search'
    | '/host/bookings'
    | '/property/$propertyId'
    | '/host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-confirmed'
    | '/bookings'
    | '/favorites'
    | '/reviews'
    | '/search'
    | '/host/bookings'
    | '/property/$propertyId'
    | '/host'
  id:
    | '__root__'
    | '/'
    | '/booking-confirmed'
    | '/bookings'
    | '/favorites'
    | '/reviews'
    | '/search'
    | '/host/bookings'
    | '/property/$propertyId'
    | '/host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  BookingsRoute: typeof BookingsRoute
  FavoritesRoute: typeof FavoritesRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  HostBookingsRoute: typeof HostBookingsRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
  HostIndexRoute: typeof HostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/host/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  BookingsRoute: BookingsRoute,
  FavoritesRoute: FavoritesRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  HostBookingsRoute: HostBookingsRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
  HostIndexRoute: HostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
